---
pagetitle: "About Marine Energy"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div class="about-body">

<div class="container about-container">

##About Marine Energy

<div class="row">
The Marine Energy (formerly MHK) Environmental Toolkit for Permitting and Licensing effort seeks to increase regulators’ understanding of Marine Energy projects and their potential environmental effects to reduce the amount of time to permit and decrease costs to develop Marine Energy projects. The Toolkit compiles and distills existing environmental, spatial, regulatory, and scientific data into one web-based platform. The current state–of-science on key topics associated with Marine Energy permitting is synthesized in the Toolkit, with live links to existing resources. It is designed to complement other DOE efforts such as the <a href = "https://openei.org/wiki/PRIMRE" target="_blank">Portal and Repository for Information on Marine Renewable Energy (PRIMRE)</a>. A series of workshops were held with state and federal regulators to provide input on the functionality of and information contained within the Toolkit, as well as create buy-in with the use of the Toolkit in the Marine Energy permitting and licensing process.
<br>
<br>
The Toolkit has four major components, integrated into one web-based platform, to increase the efficiency and effectiveness of the Marine Energy permitting process:
<br>
<br>

**Data Catalog & Mapper**
: Relevant spatial environmental datasets (e.g., <a href = "https://marinecadastre.gov/" target="_blank">MarineCadastre</a>) provide the ability to identify overlapping species, habitats, and human uses for a proposed development area, similar to <a href = "https://www.marinecadastre.gov/oceanreports/@-10737743.881037742,4753280.983019757/4" target="_blank">OceanReports</a>.

**Guidelines and Flowcharts**
: General guidelines and flowcharts for permitting are described, similar to <a href="https://openei.org/wiki/RAPID" target="_blank">RAPID</a>.

**Searchable Documents**
: Documents relevant to projects, precedent, and mitigation are searchable through the <a href="https://tethys.pnnl.gov/knowledge-base" target="_blank">Tethys Knowledge Base</a> or <a href="https://elibrary.ferc.gov/eLibrary/search" target="_blank">FERC eLibrary</a>.

**Engagement and Communication**
: Community engagement with a focus on communication and outreach between regulators, subject matter experts, stakeholders, and developers.
<br>
<br>

## Mission

The mission of the Marine Energy (formerly MHK) Environmental Toolkit for Permitting and Licensing Project is to create a one-stop-shop for the Marine Energy community to access, review, and compile relevant regulatory, spatial, and academic information to increase the efficiency of the Marine Energy permitting and licensing process.

The project has four main objectives:
<br>
<br>
**Distill** scientific knowledge into an Assessment Framework and Status Reports. 
<br>
<br>
**Develop** an easily accessible online Marine Energy Environmental Permitting Toolkit. 
<br>
<br>
**Conduct** in-person meetings and webinars with relevant regulators from federal and state agencies to share and gather input on the Toolkit and to share expert understanding of potential effects and state-of-the-science for Marine Energy projects.
<br>
<br>
**Pilot** test the Toolkit and gather lessons learned from the permitting process.
<br>
<br>

## Organizations

- <a href = "https://ecoquants.com" target="_blank">EcoQuants</a>
- <a href = "https://www.epri.com" target="_blank">Electric Power Research Institute</a>
- <a href = "http://www.emec.org.uk" target="_blank">European Marine Energy Centre Ltd.</a>
- <a href = "https://www.harveyecology.com" target="_blank">H.T. Harvey & Associates</a>
- <a href = "https://www.integral-corp.com" target="_blank">Integral Consulting Inc.</a>
- <a href = "https://kearnswest.com" target="_blank">Kearns & West</a>
- <a href = "https://www.orpc.co/" target="_blank">Ocean Renewable Power Company</a>
- <a href = "https://tethys.pnnl.gov/organization/pacific-energy-ventures-llc" target="_blank">Pacific Energy Ventures</a>
- <a href = "https://www.sandia.go" target="_blank">Sandia National Laboratories</a>
<br>
<br>

## Funding

This project is funded by the U.S. Department of Energy and was selected as a winner under Federal Opportunity Announcement DE-FOA-0001837 Marine and Hydrokinetic Technology Advancement and Data Dissemination Topic Area 3: Dissemination of Environmental Data and Analyses to Facilitate the Marine Energy Regulatory Process. 
<br>
<br>

## Disclaimer

These web services were prepared as an account of work sponsored by an agency of the United States Government. Neither the United States Government nor any agency thereof, nor any of their employees, makes any warranty, express or implied, or assumes any legal liability or responsibility for the accuracy, completeness, or usefulness of any information, apparatus, product, or process disclosed, or represents that its use would not infringe privately owned rights. Reference herein to any specific commercial product, process, or service by trade name, trademark, manufacturer, or otherwise does not necessarily constitute or imply its endorsement, recommendation, or favoring by the United States Government or an agency thereof. The views and opinions of authors expressed herein do not necessarily state or reflect those of the United States Government or any agency thereof.
<br>
<br>

</div>
</div>
</div>
