---
title: "Environmental Interactions"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

Environmental Interactions are based on Receptors (rows) x Stressors (columns) and the number of Tethys references found are listed with links out to Tethys: 

```{r}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
shelf(dplyr, DT, glue, here, kableExtra, knitr, readr, tidyr)

s_r_csv <- ifelse(
  Sys.info()['sysname'] == "Linux",
  "/share/github/mhk-env_shiny-apps/data/tethys_intxns.csv",
  here("data/tethys_stressor_receptor.csv")) # OLD; now updated on server within shiny repo

s_r <- read_csv(s_r_csv)

s_r %>% 
  mutate(
    link     = 
      if_else(
        num_refs > 0,
        glue("<a href='{url}' target='_blank'>{if_else(num_refs == 50, '50+', as.character(num_refs))}</a>"),
        "0")) %>% 
  select(stressor, receptor, link) %>% 
  pivot_wider(names_from = "stressor", values_from = link) %>% 
  # datatable(
  #   escape    = F,
  #   rownames  = T,
  #   options   = list(
  #       pageLength = Inf, 
  #       #dom        = 't',
  #       searching  = F, 
  #       bPaginate  = F, 
  #       info       = F)) %>% 
  kable("html", escape = F) %>%
  kable_styling(
    "striped", full_width = F)
```

