---
title: "FERC Documents"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r init}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
shelf(crosstalk, dplyr, DT, glue, readr)

ferc_docs_csv <- "/share/github/mhk-env_shiny-apps/data/ferc_docs.csv"

d <- read_csv(ferc_docs_csv) %>% 
  mutate(
    doc = ifelse(
      !is.na(url),
      glue("<a href='{url}'>{doc}</a>"),
      doc)) %>% 
  select(-url)
```

```{r explore, eval=F}
d %>%
  filter(Technology == "Tidal") %>%
  datatable()

table(d$Technology)
table(d$Stressor)
table(d$Receptor)
table(d$`Specific Receptor`)

datatable(d)

tbl %>% 
  group_by(Technology, `Management Measure Category`, `Phase of Project`, Stressor, Receptor) %>% 
  summarize(n = n())
names(tbl)
```

```{r}
# names(d)
sd <- SharedData$new(d)

bscols(widths = c(6,6,6,6),
    filter_select("selTech"    , "Technology", sd, group=~technology, multiple = T),
    filter_select("selPhase"   , "Phase"     , sd, group=~phase     , multiple = T),
    filter_select("selReceptor", "Receptor"  , sd, group=~receptor  , multiple = T),
    filter_select("selStressor", "Stressor"  , sd, group=~stressor  , multiple = T),
    filter_checkbox(
      "presented_as_potential_interaction", 
      "Presented as potential interaction?", 
      sd, ~presented_as_potential_interaction, inline = TRUE),
    filter_checkbox(
      "decribed_from_observations_at_the_project_site", 
      "Described from observations at the project site?", 
      sd, ~decribed_from_observations_at_the_project_site, inline = TRUE),
    filter_checkbox(
      "monitoring_plan_(mp)", 
      "Monitoring Plan (MP)?", 
      sd, ~`monitoring_plan_(mp)`, inline = TRUE),
    filter_checkbox(
      "adaptive_management_plan_(amp)", 
      "Adaptive Management Plan (AMP)?", 
      sd, ~`adaptive_management_plan_(amp)`, inline = TRUE),
    filter_checkbox(
      "protection_mitigation_and_enhancement", 
      "Protection, mitigation, and ehnhancement?", 
      sd, ~protection_mitigation_and_enhancement, inline = TRUE),
    filter_checkbox(
      "bmps_applied", 
      "Best Management Practices (BMP) applied?", 
      sd, ~bmps_applied, inline = TRUE))
sd %>% 
datatable(
  escape = F,
  colnames = c(
    "Document"               = "doc",
    "Key Effects"            = "key_effects",
    "Key Interaction Detail" = "key_interaction_detail",
    "MP Notes"               = "notes_mp",
    "AMP Notes"              = "notes_amp",
    "General Notes"          = "notes_general",
    "Receptor"               = "receptor",
    "Stressor"               = "stressor",
    "Technology"             = "technology",
    "Project Phase"          = "phase",
    "Presented as potential interaction?" = "presented_as_potential_interaction",
    "Described from observations at the project site?" = "decribed_from_observations_at_the_project_site",
    "MP" = "monitoring_plan_(mp)",
    "AMP" = "adaptive_management_plan_(amp)",
    "Protection, mitigation, and ehnhancement?" = "protection_mitigation_and_enhancement",
    "BMPs applied?" = "bmps_applied"))
```