---
title: "Management Measures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

Source: [Management Measures Tool for Marine Renewable Energy | Tethys](https://tethys.pnnl.gov/management-measures)

```{r init}
library(here)
library(readr)
library(dplyr)
library(rvest)
library(DT)
library(crosstalk)

url     <- "https://tethys.pnnl.gov/management-measures"
mgt_csv <- here("data/mgt.csv")
redo    <- F

if (!file.exists(mgt_csv) | redo){
  read_html(url) %>% 
    html_table() %>% 
    .[[1]] %>% 
    write_csv(mgt_csv)
}
d <- read_csv(mgt_csv) %>% 
  rename(
    Category = `Management Measure Category`,
    Phase    = `Phase of Project`)
```

```{r explore, eval=F}
d %>%
  filter(Technology == "Tidal") %>%
  datatable()

table(d$Technology)
table(d$Stressor)
table(d$Receptor)
table(d$`Specific Receptor`)

datatable(d)

tbl %>% 
  group_by(Technology, `Management Measure Category`, `Phase of Project`, Stressor, Receptor) %>% 
  summarize(n = n())
names(tbl)
```

```{r}

sd <- SharedData$new(d)

bscols(widths = c(4,4,4,6,6),
    filter_select("selTech"    , "Technology", sd, group=~Technology, multiple = T),
    filter_select("selCategory", "Category"  , sd, group=~Category  , multiple = T),
    filter_select("selPhase"   , "Phase"     , sd, group=~Phase     , multiple = T),
    filter_select("selReceptor", "Receptor"  , sd, group=~Receptor  , multiple = T),
    filter_select("selStressor", "Stressor"  , sd, group=~Stressor  , multiple = T))

datatable(sd)
```