---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
.graphic-container {
  width: 100%;
  height: 900px;
  position: relative;
  text-align: center;
  display: block;
}
.mermaid {
  width:100%;
  height:100%;
  position:absolute;
  top:0;
  left:0;
  z-index:1;
  /* margin: auto; */
  /* display: block; */
}
</style>

<div class="mermaid">
graph TD
grid-->|Yes|tethys
grid-->|No|state
state-->|Yes|acoe
state-->|No|boem
grid{fa:fa-arrows-alt<br>Is the project<br>grid connected?}
tethys[Tethys: MRE<br/>regulatory frameworks]
click tethys "https://tethys.pnnl.gov/regulatory-frameworks-marine-renewable-energy#United%20States%20of%20America" "Regulatory Frameworks for Marine Renewable Energy: USA"
state{fa:fa-institution<br>Is the project<br>in state waters?}
boem[lead: BOEM]
acoe[lead: ACOE/state]
</div>

<div class="graphic-container">
<div class="mermaid">
  graph TD
  grid{<center>fa:fa-arrows-alt</center>Is the project<br>grid connected?}
  ferc[FERC Process<center>fas:fa-external-link-alt</center>]
  territory{<center>fa:fa-institution</center>Is the project<br>in state waters?}
  boem[BOEM Regulatory <br>Framework and <br>Guidelines<center>fas:fa-external-link-alt</center>]
  lead{<center>fas:fa-people-arrows</center>Who is leading<br>the project?}
  state[State Process<center>fas:fa-external-link-alt</center>]
  acoe[ACOE Process<center>fas:fa-external-link-alt</center>]

  grid-->|Yes|ferc
  grid-->|No|territory
  territory-->|Yes|lead
  territory-->|No|boem
  lead --> state
  lead --> acoe
  
  click ferc "./regs-ferc.html"
  click acoe "./regs-acoe.html"
  click state "./regs-state.html"
  click boem "https://www.boem.gov/renewable-energy/regulatory-framework-and-guidelines" _blank
  
  classDef endNode fill:#99d1b3,stroke:#333,stroke-width:2px,font-size:90%,line-height:1.5,stroke-opacity:0.8;
  classDef endNode:hover fill:#75a189;
  classDef endNode:active fill:#75a189;
  
  classDef decisionNode fill:#96b0e0,stroke:#333,stroke-width:3px,font-size:90%,line-height:1.5;
  
  class ferc,acoe,state,boem endNode
  class grid,territory,lead decisionNode
</div>
</div>

<!-- mermaid diagram initialization -->
<script>
var config = {
 startOnLoad:true,
 flowchart:{
 useMaxWidth:true,
 htmlLabels:true,
 curve:'cardinal'
 },
 securityLevel:'loose'
 };
 mermaid.initialize(config);
</script>

