graph TD
grid-->|Yes|tethys
grid-->|No|state
state-->|Yes|acoe
state-->|No|boem
grid{fa:fa-arrows-alt<br>Is the project<br>grid connected?}
tethys[/Tethys: MRE<br/>regulatory frameworks/]
%% click tethys "https://tethys.pnnl.gov/regulatory-frameworks-marine-renewable-energy#United%20States%20of%20America" "Regulatory Frameworks for Marine Renewable Energy: USA"
click tethys "./modals/test_modal.html" "Regulatory Frameworks for Marine Renewable Energy: USA"
state{fa:fa-institution<br>Is the project<br>in state waters?}
boem[lead: BOEM]
acoe[lead: ACOE/state]

%% see in mermaid-live-editor: https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbmdyaWQtLT58WWVzfHRldGh5c1xuZ3JpZC0tPnxOb3xzdGF0ZVxuc3RhdGUtLT58WWVzfGFjb2VcbnN0YXRlLS0-fE5vfGJvZW1cbmdyaWR7ZmE6ZmEtYXJyb3dzLWFsdDxicj5JcyB0aGUgcHJvamVjdDxicj5ncmlkIGNvbm5lY3RlZD99XG50ZXRoeXNbVGV0aHlzOiBNUkU8YnIvPnJlZ3VsYXRvcnkgZnJhbWV3b3Jrc11cbmNsaWNrIHRldGh5cyBcImh0dHBzOi8vdGV0aHlzLnBubmwuZ292L3JlZ3VsYXRvcnktZnJhbWV3b3Jrcy1tYXJpbmUtcmVuZXdhYmxlLWVuZXJneSNVbml0ZWQlMjBTdGF0ZXMlMjBvZiUyMEFtZXJpY2FcIiBcIlJlZ3VsYXRvcnkgRnJhbWV3b3JrcyBmb3IgTWFyaW5lIFJlbmV3YWJsZSBFbmVyZ3k6IFVTQVwiXG5zdGF0ZXtmYTpmYS1pbnN0aXR1dGlvbjxicj5JcyB0aGUgcHJvamVjdDxicj5pbiBzdGF0ZSB3YXRlcnM_fVxuYm9lbVtsZWFkOiBCT0VNXVxuYWNvZVtsZWFkOiBBQ09FL3N0YXRlXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9
