%% see in mermaid-live-editor: https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbmdyaWQtLT58WWVzfHRldGh5c1xuZ3JpZC0tPnxOb3xzdGF0ZVxuc3RhdGUtLT58WWVzfGFjb2VcbnN0YXRlLS0-fE5vfGJvZW1cbmdyaWR7ZmE6ZmEtYXJyb3dzLWFsdCBjbGFzcyBmYS1sZyA8YnI-SXMgdGhlIHByb2plY3Q8YnI-Z3JpZCBjb25uZWN0ZWQ_fVxudGV0aHlzW1RldGh5czogTVJFPGJyLz5yZWd1bGF0b3J5IGZyYW1ld29ya3NdXG5jbGljayB0ZXRoeXMgXCJodHRwczovL3RldGh5cy5wbm5sLmdvdi9yZWd1bGF0b3J5LWZyYW1ld29ya3MtbWFyaW5lLXJlbmV3YWJsZS1lbmVyZ3kjVW5pdGVkJTIwU3RhdGVzJTIwb2YlMjBBbWVyaWNhXCIgXCJSZWd1bGF0b3J5IEZyYW1ld29ya3MgZm9yIE1hcmluZSBSZW5ld2FibGUgRW5lcmd5OiBVU0FcIlxuc3RhdGV7ZmE6ZmEtaW5zdGl0dXRpb248YnI-SXMgdGhlIHByb2plY3Q8YnI-aW4gc3RhdGUgd2F0ZXJzP31cbmJvZW1bbGVhZDogQk9FTV1cbmFjb2VbbGVhZDogQUNPRS9zdGF0ZV1cbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9
graph TD
grid-->|Yes|tethys
grid-->|No|state
state-->|Yes|acoe
state-->|No|boem
grid{fa:fa-arrows-alt class fa-lg <br>Is the project<br>grid connected?}
tethys[Tethys: MRE<br/>regulatory frameworks]
click tethys "https://tethys.pnnl.gov/regulatory-frameworks-marine-renewable-energy#United%20States%20of%20America" "Regulatory Frameworks for Marine Renewable Energy: USA"
state{fa:fa-institution<br>Is the project<br>in state waters?}
boem[lead: BOEM]
acoe[lead: ACOE/state]
