graph TD
grid{<center>fa:fa-arrows-alt</center>Is the project<br>grid connected?}
tethys[Tethys: MRE<br/>regulatory frameworks<center>fas:fa-external-link-alt</center>]
territory{<center>fa:fa-institution</center>Is the project<br>in state waters?}
boem[lead: BOEM<center>fas:fa-external-link-alt</center>]
lead{<center>fas:fa-people-arrows</center>Who is leading<br>the project?}
state[lead: State<center>fas:fa-external-link-alt</center>]
acoe[lead: ACOE<center>fas:fa-external-link-alt</center>]

grid-->|Yes|tethys
grid-->|No|territory
territory-->|Yes|lead
territory-->|No|boem
lead --> state
lead --> acoe

click tethys "https://tethys.pnnl.gov/regulatory-frameworks-marine-renewable-energy#United%20States%20of%20America"
click acoe "./regs-acoe.html"
click state "./regs-state.html"
click boem "./regs-boem.html"