%% edit with https://mermaid-js.github.io/mermaid-live-editor

graph TD
grid{fa:fa-arrows-alt Is the project<br>grid connected?}
ferc[FERC Process fas:fa-external-link]
territory{fa:fa-institution Is the project<br>in state waters?}
boem[BOEM Regulatory <br>Framework and <br>Guidelines fas:fa-external-link-alt]
lead{fa:fa-people-arrows Who is leading<br>the project?}
state[State Process]
acoe[ACOE Process]

grid-->|Yes|ferc
grid-->|No|territory
territory-->|Yes|lead
territory-->|No|boem
lead --> state
lead --> acoe

click ferc "./regs-ferc.html"
click acoe "./regs-acoe.html"
click state "./regs-state.html"
click boem "https://www.boem.gov/renewable-energy/regulatory-framework-and-guidelines" _blank

classDef endNode fill:#99d1b3,stroke:#333,stroke-width:2px,font-size:90%,line-height:1.5,stroke-opacity:0.8;
classDef endNode:hover fill:#75a189;
classDef endNode:active fill:#75a189;

classDef decisionNode fill:#96b0e0,stroke:#333,stroke-width:3px,font-size:90%,line-height:1.5;

class ferc,acoe,state,boem endNode
class grid,territory,lead decisionNode